import type { EnrichmentResult } from "@tadoru/core";

const mockEnrichments: Record<string, EnrichmentResult> = {
  "示唆": {
    card: {
      reading: "しさ",
      meanings: ["suggestion", "hint", "namyok"],
      exampleSentence: "彼の発言は今後の方針を示唆していた。",
      notes: "Often used in formal writing to describe an implied meaning or indication.",
      nodeType: "word",
    },
    connections: [
      {
        surface: "示す",
        reading: "しめす",
        meanings: ["to show", "to indicate"],
        edgeType: "shares_kanji",
        weight: 0.88,
      },
      {
        surface: "暗示",
        reading: "あんじ",
        meanings: ["suggestion", "implication"],
        edgeType: "semantic_similar",
        weight: 0.72,
      },
      {
        surface: "示唆する",
        reading: "しさする",
        meanings: ["to suggest", "to imply"],
        edgeType: "grammar_uses",
        weight: 0.83,
      },
    ],
  },
  "食べる": {
    card: {
      reading: "たべる",
      meanings: ["to eat", "to consume"],
      exampleSentence: "朝ごはんを食べる前にコーヒーを入れた。",
      notes: "Ichidan verb. Common foundational vocabulary.",
      nodeType: "word",
    },
    connections: [
      {
        surface: "食事",
        reading: "しょくじ",
        meanings: ["meal", "dining"],
        edgeType: "shares_kanji",
        weight: 0.84,
      },
      {
        surface: "食べ物",
        reading: "たべもの",
        meanings: ["food"],
        edgeType: "derived_from",
        weight: 0.79,
      },
      {
        surface: "食う",
        reading: "くう",
        meanings: ["to eat", "to live on"],
        edgeType: "semantic_similar",
        weight: 0.55,
      },
    ],
  },
  "走る": {
    card: {
      reading: "はしる",
      meanings: ["to run"],
      exampleSentence: "駅まで全力で走った。",
      notes: "Godan verb. Frequently contrasted with 歩く.",
      nodeType: "word",
    },
    connections: [
      {
        surface: "走者",
        reading: "そうしゃ",
        meanings: ["runner"],
        edgeType: "shares_kanji",
        weight: 0.82,
      },
      {
        surface: "駆ける",
        reading: "かける",
        meanings: ["to dash", "to gallop"],
        edgeType: "semantic_similar",
        weight: 0.66,
      },
      {
        surface: "競走",
        reading: "きょうそう",
        meanings: ["race"],
        edgeType: "co_occurs",
        weight: 0.47,
      },
    ],
  },
  "にもかかわらず": {
    card: {
      reading: "にもかかわらず",
      meanings: ["despite", "in spite of", "although"],
      exampleSentence: "雨にもかかわらず、試合は予定どおり行われた。",
      notes: "Formal grammar pattern. Often traced back to 構う and the phrase にも関わらず.",
      nodeType: "grammar",
    },
    connections: [
      {
        surface: "構う",
        reading: "かまう",
        meanings: ["to mind", "to care about"],
        edgeType: "etymology",
        weight: 0.94,
      },
      {
        surface: "関わる",
        reading: "かかわる",
        meanings: ["to be related", "to concern"],
        edgeType: "derived_from",
        weight: 0.7,
      },
      {
        surface: "それでも",
        reading: "それでも",
        meanings: ["even so", "nevertheless"],
        edgeType: "semantic_similar",
        weight: 0.51,
      },
    ],
  },
};

function createGenericEnrichment(surface: string): EnrichmentResult {
  return {
    card: {
      reading: surface,
      meanings: [`${surface} (mock meaning)`],
      exampleSentence: `${surface} を使ったモックの例文です。`,
      notes: "Generated by the deterministic E2E mock service.",
      nodeType: "word",
    },
    connections: [
      {
        surface: `${surface}する`,
        reading: `${surface}する`,
        meanings: [`to do ${surface}`],
        edgeType: "grammar_uses",
        weight: 0.62,
      },
      {
        surface: `${surface}関連`,
        reading: `${surface}かんれん`,
        meanings: [`${surface} related`],
        edgeType: "co_occurs",
        weight: 0.41,
      },
    ],
  };
}

export async function enrichWordMock(surface: string): Promise<EnrichmentResult> {
  const normalized = surface.trim();
  return mockEnrichments[normalized] ?? createGenericEnrichment(normalized);
}
